name: scrape
description: A sample command-line application.
version: 1.0.0
homepage: https://www.example.com
author: guruliciousjide@gmail.com <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  html: ^0.13.3+3
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
